name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.1'

      - name: Create .env file from secrets
        run: |
          echo "VITE_API_URL=https://localhost:8000" >> .env
          echo "VITE_FB_API_KEY=${{ secrets.VITE_FB_API_KEY }}" >> .env
          echo "VITE_FB_MSG_SENDER_ID=${{ secrets.VITE_FB_MSG_SENDER_ID }}" >> .env
          echo "VITE_FB_APP_ID=${{ secrets.VITE_FB_APP_ID }}" >> .env
          echo "VITE_FB_MEASUREMENT_ID=${{ secrets.VITE_FB_MEASUREMENT_ID }}" >> .env
          echo "VITE_FB_AUTH_DOMAIN=<<YourWebsiteDomain>>.firebaseapp.com" >> .env
          echo "VITE_FB_PROJECT_ID=<<YourFirebasePorjectID>>" >> .env
          echo "VITE_FB_STORAGE_BUCKET=<<YourFirebaseStorageBucketID>>.firebasestorage.app" >> .env

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Build frontend (SSG Application)
        run: pnpm run build     # CSR
        # run: pnpm run build-ssg   # SSG

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: <<YourFirebasePorjectID>>
          entryPoint: frontend
          expires: 7d
          # channelId: preview
          channelId: live
